### ISSUE TITLE
Pixels are not same size

### ISSUE THREAD

**Issue by jraregris** [iterate/logo-png#1]
![Screenshot 2019-08-23 at 12 59 24](https://user-images.githubusercontent.com/37021/63588194-37079e80-c5a6-11e9-9aa7-862bb7168b35.png)

I assume that the resizing should be locked to multiples of the original.

Screenshot from Firefox Quantum 69.0b13 (64-bit) on Macos 10.14.6 (18G87)

**Comment by sindreij** [comment]
Looks like some weird scaling on the browser or OS.
